name: "Ernesto Tagwerker: Founder & CTO at OmbuLabs.ai"
title: "Ernesto Tagwerker: Founder & CTO at OmbuLabs.ai"
tagline: "Software Development, AI & Ruby on Rails"
description: "Founder & CTO at OmbuLabs.ai, building custom AI solutions and helping companies upgrade their Ruby and Rails applications."
meta_description: "Articles about software development, AI, Ruby on Rails upgrades, and building sustainable software businesses by Ernesto Tagwerker, Founder & CTO at OmbuLabs.ai."
destination: ./public
highlighter: rouge
logo: true
paginate: 3
domain_name: 'https://etagwerker'
permalink: none
category_dir: 'tags'
excerpt_separator: "<!--more-->"
author_title_prefix: "Articles by "
timezone: America/New_York

# Details for the RSS feed generator
url:            'https://etagwerker.com'
author:         '@etagwerker'
feed:
  path: rss.xml
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

exclude: [vendor]
plugins: ['jekyll-titleize', 'jekyll-paginate', 'jekyll-feed']

sass:
  style: compressed

authors:
  etagwerker:
    display_name: Ernesto Tagwerker
    gravatar: 9299203e7e9b9ae35e39eb66f3155f15
    email: ernesto@ombulabs.com
    twitter: etagwerker
    github: etagwerker
